version: "3"

services:
  web:
    container_name: mongo-app-example
    restart: always
    build: .
    ports: 
      - "5000:3000"
    volumes:
      - .:/usr/src/app
  database:
    container_name: mongo-db-example
    image: mongo
    ports:
      - "27018:27017"